/* THE FRONT PAGE'S WORDS (T-2131). Every word of the approved mock-up (palette C,
   version 3), in the mock-up's order, and nothing else: the page and its moving parts
   read them from here by key, and test/front-words.test.ts fails if one they ask for
   is missing. English only, as the mock-up is. A value may carry <em>, <b>, <small>,
   <br>, <span class="soon"> and <span class="gap"> and no other markup (rich.tsx).
   {imprint} is Imprint's hostname, from lib/links.ts; {n}, {w}, {k}, {gap} and {where}
   are filled in by the demo. */

export const W = {
  /* the band */
  'name': 'Imprint',
  'a.brand': 'Snow AI Imprint',
  'a.main': 'Main',
  'brand': 'Snow AI Imprint',
  'nav.f': 'How it works',
  'nav.d': 'Try the outline',
  'nav.i': 'What’s included',
  'nav.fam': 'The family',
  'nav.q': 'Questions',
  'nav.in': 'Sign in',
  'nav.open': 'Open the studio',
  'notice': '<b>Being built, in steps.</b> Today the studio has the Snow AI sign-in and your list of books. The book steps on this page come next, in the order shown.',

  /* the hero */
  'hero.eb': 'Nonfiction, for professionals',
  'hero.h': 'Put your name on <em>a book.</em>',
  'hero.p': 'Imprint is where a book is written from your own expertise: an idea, a title, an outline of chapters, drafts you edit, and a Word file and a PDF at the end. For the client guide or the lead-magnet book only you could write.',
  'hero.c1': 'Open the studio',
  'hero.c2': 'Try the outline here',
  'hero.fine': 'The book, the author and the chapters on this page are invented examples.',
  'hero.a.win': 'Example: a book outline growing chapter by chapter, one chapter drafted from its brief, then the Word and PDF files',
  'hero.url': '{imprint}/studio/book/renewal-checklist',
  'ex': 'In build · example',
  'book': 'The Renewal Checklist',
  'book.sub': 'A short client guide to reading your own policy before it renews',
  'book.by': 'Ari Vance',
  'crumb.outline': 'Outline',
  'crumb.ch2': 'Chapter 2',
  'crumb.export': 'Export',
  'saved': 'Saved',
  'export': 'Export',
  'rail.studio': 'Studio',
  'rail.yours': 'Your books',
  'rail.books': 'Books',
  'rail.this': 'This book',
  'rail.idea': 'Idea',
  'rail.title': 'Title',
  'rail.outline': 'Outline',
  'rail.chapters': 'Chapters',
  'rail.sources': 'Sources',
  'rail.ai': 'AI disclosure',
  'rail.export': 'Export',
  'h.outline': 'Outline',
  'h.add': 'Add a chapter',
  'h.reorder': 'Reorder',
  'h.range': '8 to 14 chapters',
  'h.draftBtn': 'Draft this chapter',
  'st.drafting': 'Drafting',
  'st.outline': 'Outline',
  'st.done': 'Done',
  'st.edited': 'Edited',
  'brief': 'Brief',
  'h.brief': 'Reading the declarations page: what each line means, and the two numbers to check first.',
  'src.1': 'declarations-sample.pdf',
  'src.2': 'renewal-notes.md',
  'src.3': 'agency-faq.pdf',
  'ch2.p1': 'Most people meet their declarations page once, when the policy starts, and never again. It is worth a second look every renewal.',
  'h.prov': 'AI draft · {w} words',
  'h.draft': 'Start at the top: the named insured, the policy period and the address the cover applies to. Next come the limits, the most the policy will pay, and the deductible, what you pay first.',
  'h.exportLine': 'Title page · Copyright · Contents · 8 chapters',
  'h.gap': 'A final file waits for 1 gap: Chapter 2 still says [need a source].',
  'h.ok': 'Every gap is filled. The final files are ready.',
  'docx': 'DOCX',
  'pdf': 'PDF',
  'file.docx': 'The Renewal Checklist.docx',
  'file.pdf': 'The Renewal Checklist.pdf',
  'file.word8': 'Word · 8 chapters',
  'file.pdf8': 'PDF · 8 chapters',
  'h.toast': 'Word and PDF made · ready to download',
  'hero.a.sheet': 'Example: a page of the finished book',
  'contents': 'Contents',
  'sheet.ch': 'Chapter 2',
  'sheet.t': 'Reading the declarations page',
  'sheet.p2': 'Start at the top: the named insured, the policy period and the address the cover applies to. A wrong address is the commonest mistake <span class="gap">[need a source]</span>.',
  'pause': 'Pause',
  'play': 'Play',
  'step.0': 'Outline',
  'step.1': 'Draft a chapter',
  'step.2': 'Word and PDF',

  /* the eight chapters of the invented book */
  'ch.1': 'Why renewal is the moment to look',
  'ch.1s': 'The one time a year the terms can change without you asking',
  'ch.2': 'Reading the declarations page',
  'ch.2s': 'What each line means, and the two numbers to check first',
  'ch.3': 'The three questions to ask your agent',
  'ch.3s': 'Short questions that get useful answers',
  'ch.4': 'Keeping your records in one place',
  'ch.4s': 'What to keep, for how long, and where',
  'ch.5': 'What changes when your life changes',
  'ch.5s': 'A move, a new car, a new business',
  'ch.6': 'Comparing a renewal offer',
  'ch.6s': 'Line by line, against last year',
  'ch.7': 'When to ask for a review',
  'ch.7s': 'The moments that are worth a call',
  'ch.8': 'A one-page checklist to keep',
  'ch.8s': 'Everything above, on one page',

  /* works with */
  'a.strip': 'Works with',
  'strip.l': 'Built on the family',
  'strip.dict': 'Dictation',
  'strip.dictE': 'every box',
  'strip.ask': 'Snow AI Ask',
  'strip.askE': 'ideas, outlines, drafts',
  'strip.reader': 'Snow AI Reader',
  'strip.readerE': 'PDF sources',
  'strip.render': 'Snow AI Render',
  'strip.renderE': 'Word and PDF',
  'strip.ai': 'AI disclosure',
  'strip.aiE': 'for store forms',
  'strip.login': 'One Snow AI login',

  /* who it's for */
  'who.eb': 'Who it’s for',
  'who.h': 'You already know the book. <em>It just isn’t written yet.</em>',
  'who.1t': 'A guide clients keep',
  'who.1h': 'Insurance agents',
  'who.1p': 'The questions you answer every renewal, put in order once, with your name on the cover.',
  'who.2t': 'Before the season starts',
  'who.2h': 'Tax preparers',
  'who.2p': 'What clients should gather, what changed and what to expect, as a short book you hand out instead of repeating.',
  'who.3t': 'Your method, written down',
  'who.3h': 'Coaches and consultants',
  'who.3p': 'The framework you teach, chapter by chapter: a lead-magnet book that shows how you think before the first call.',
  'fact.1': 'steps from an idea to a file',
  'fact.2': 'title and subtitle options to choose from, or write your own',
  'fact.3': 'chapters in an outline, each with a summary and its points',
  'fact.4': 'files at the end: Word and PDF',
  'fact.5': 'words of yours ever replaced by a draft',

  /* how it works */
  'a.features': 'How it works',
  'feat.eb': 'How it works',
  'feat.h': 'From an idea to a file you can hand out.',
  'feat.p': 'Each step below is being built, in this order. The studio says “In build” wherever one isn’t ready.',
  'f1.ib': 'In build · step 1 and 2',
  'f1.eb': 'The idea and the title',
  'f1.h': 'Say what it’s about. Pick from five titles.',
  'f1.p': 'Talk or type the idea: what the book is about, who it’s for and how it should sound. Imprint comes back with five title and subtitle options and one sentence that positions the book. Pick one, edit it, or write your own.',
  'f1.t1': 'A mic on every box',
  'f1.t2': 'Your name for the title page and the copyright line',
  'f1.t3': 'An optional “About the author” page',
  'f1.a': 'Example: five title options for an invented book',
  'f1.untitled': 'Untitled book',
  'f1.idea': 'The idea',
  'f1.ideaV': 'A short guide my clients can read before renewal, so they know what to check on their own policy.',
  'f1.o2': 'Before You Renew',
  'f1.o2s': 'What to look at, what to ask and what to keep',
  'f1.o3': 'Read Your Policy',
  'f1.o3s': 'A plain walk through the pages most people skip',
  'f1.note': 'Example · invented · 3 of 5 options shown',
  'f2.ib': 'In build · step 3',
  'f2.eb': 'The outline',
  'f2.h': 'Eight to fourteen chapters, each with its brief.',
  'f2.p': 'The outline gives every chapter a title, a summary and the points it should make. Reorder them, rename them, add one or delete one. The brief is what a chapter’s draft is written from, so it’s worth getting right.',
  'f2.t1': 'Each chapter shows where it stands: Outline, Drafting, Edited, Done',
  'f2.t2': 'A target length for each chapter',
  'f2.t3': 'Your outline, your order',
  'f2.a': 'Example: an outline of chapters',
  'f2.crumb': 'Outline · 8 chapters',
  'f2.note': 'Example · invented · 5 of 8 chapters shown',
  'f3.ib': 'In build · step 4',
  'f3.eb': 'The chapters',
  'f3.h': 'Write it yourself, or draft it from the brief and your sources.',
  'f3.p': 'Each chapter has its own workspace. “Draft this chapter” writes from the chapter’s brief and the sources you tick, and nothing else. The new paragraphs are added after your own words; nothing you wrote is replaced.',
  'f3.t1': 'A missing fact is marked <span class="gap">[need a figure]</span> or <span class="gap">[need a source]</span>',
  'f3.t2': 'Sources are paraphrased, not copied in long passages',
  'f3.t3': 'A PDF source is read by Snow AI Reader; only its words are kept',
  'f3.note': 'Every book is general education, never medical, tax or legal advice for one reader, and never holds a real person’s health details.',
  'f3.a': 'Example: a chapter with a draft added after the author\'s words',
  'f3.crumb': 'Chapter 2 · Reading the declarations page',
  'brief.1': 'What each line of the page means',
  'brief.2': 'The two numbers to check first',
  'brief.3': 'What to do when something is wrong',
  'f3.prov': 'AI draft · 212 words',
  'f3.d1': 'Start at the top: the named insured, the policy period and the address the cover applies to. A wrong address is a common mistake <span class="gap">[need a source]</span>.',
  'f3.d2': 'Next come the limits, the most the policy will pay, and the deductible, what you pay first.',
  'f4.ib': 'In build · with step 4',
  'f4.eb': 'Honest about AI',
  'f4.h': 'A count of what AI wrote, for the form that asks.',
  'f4.p': 'Amazon KDP asks whether a book contains AI-generated text, and enforces it. Every time a draft adds words, Imprint records how many. The disclosure helper adds them up per chapter and gives you a statement to adapt for a store’s form.',
  'f4.t1': 'Editing never erases the record of what was inserted',
  'f4.t2': 'It says plainly that it can’t see your later rewriting',
  'f4.t3': 'A helper, not legal advice, and no promise of what a store decides',
  'f4.a': 'Example: the AI disclosure helper',
  'th.chapter': 'Chapter',
  'th.words': 'Words drafted by AI',
  'f4.total': 'Total, 8 chapters',
  'f4.stmt': '“Parts of this book were first drafted with AI assistance from the author’s own outline and sources, then reviewed and edited by the author.” Adapt it for the store’s form.',
  'f5.ib': 'In build · step 5',
  'f5.eb': 'The files',
  'f5.h': 'A Word file and a PDF, ready to hand out.',
  'f5.p': 'With a title page, a copyright page and contents, made by Snow AI Render. A final file waits until every gap is filled, and names the chapters still holding one. A draft export is always there, with a DRAFT line at the head of every chapter.',
  'f5.t1': 'Nothing publishes or sends: you download the files',
  'f5.t2': 'Do what you like with them: print, email, upload',
  'f5.note': '<span class="soon">Later</span> EPUB, a print-ready PDF with trim size and bleed, a cover, and Word import.',
  'f5.a': 'Example: the title page, contents and a chapter of the exported book',
  'f5.sub': 'A short client guide',
  'f5.c1': '1 · Why renewal…',
  'f5.c2': '2 · Reading the…',
  'f5.c3': '3 · The three…',
  'f5.c4': '4 · Keeping your…',
  'f5.c5': '5 · What changes…',
  'draftL': 'DRAFT',

  /* the demo */
  'demo.eb': 'Try it here',
  'demo.h': 'Shape the outline, draft a chapter, make the files.',
  'demo.p': 'A working model of the steps being built, on an invented book. Reorder the chapters, draft a chapter, fill its gap and try the export. Nothing here leaves this page.',
  'demo.tabs': 'Steps',
  'tab.out': 'Outline',
  'tab.ch': 'A chapter',
  'tab.ex': 'Files',
  'tab.ai': 'AI disclosure',
  'demo.url': '{imprint}/studio/book/renewal-checklist',
  'o.help': 'Click a title to rename it. Move chapters up or down, delete one, or add one.',
  'o.count': '{n} chapters',
  'o.newL': 'New chapter title',
  'o.newPh': 'A new chapter title',
  'o.add': 'Add a chapter',
  'o.note': 'An outline holds 8 to 14 chapters.',
  'o.note14': 'That is 14, the most an outline holds.',
  'o.note8': 'An outline holds 8 to 14 chapters, so none can be deleted below 8.',
  'o.titleL': 'Chapter {n} title',
  'o.up': 'Move chapter {n} up',
  'o.down': 'Move chapter {n} down',
  'o.del': 'Delete chapter {n}',
  'o.open': 'This chapter is open on the next tab',
  'untitledCh': 'Untitled chapter',
  'c.title': 'Chapter {n} · {t}',
  'c.help': 'Your own words are in the box. Tick the sources the draft may use, then draft it.',
  'c.bodyL': 'Chapter text',
  'c.draft': 'Draft this chapter',
  'c.more': 'Draft more',
  'c.fill': 'Fill the gap',
  'c.note': 'The draft is added after your words. Nothing you wrote is replaced.',
  'c.added': 'Added {w} words after yours. Nothing you wrote was replaced.',
  'c.brief': 'What each line of the page means, the two numbers to check first, and what to do when something is wrong.',
  'c.sources': 'Sources for this chapter',
  'c.drafted': 'Drafted by AI in this chapter',
  'c.words': 'words',
  'c.kept': 'Kept as a record, even if you rewrite them later.',
  'c.para1': 'Start at the top: the named insured, the policy period and the address the cover applies to. A wrong address is a common mistake [need a source].',
  'c.para2': 'Next come the limits, the most the policy will pay, and the deductible, what you pay first. These are the two numbers to check before anything else.',
  'c.para3': 'If something on the page is wrong, write it down and ask for a corrected page before the renewal date.',
  'c.none': '[need a source] The brief asks what each line of the page means; no source was ticked to say so.',
  'c.fillWith': ', as the sample page in renewal-notes shows',
  'e.h': 'Export',
  'e.p': 'Title page, copyright page, contents and {n} chapters.',
  'e.where': 'Chapter {n}',
  'e.gap': 'A final file waits for 1 gap: {where} still says {gap}.',
  'e.ok': 'Every gap is filled. A final file can be made.',
  'e.final': 'Make the final Word and PDF',
  'e.draft': 'Make a draft export',
  'e.note': 'In Imprint this downloads a .docx and a .pdf, made by Snow AI Render. Here it shows the first page.',
  'e.prev': 'Previous page',
  'e.next': 'Next page',
  'e.doneFinal': '<b>Final files made.</b> The Renewal Checklist.docx and The Renewal Checklist.pdf, {n} chapters.',
  'e.doneDraft': '<b>Draft export made.</b> Every chapter starts with a DRAFT line.',
  'e.doneDraftGap': '<b>Draft export made.</b> Every chapter starts with a DRAFT line, and the gaps are left as they are.',
  'a.help': 'The words AI drafted, per chapter, from the record each draft leaves.',
  'a.total': 'Total',
  'a.stmtH': 'A statement to adapt',
  'a.stmtSome': 'Parts of this book (about {w} words, in one chapter) were first drafted with AI assistance from the author’s own outline and sources, then reviewed and edited by the author.',
  'a.stmtNone': 'No text in this book was drafted by AI in Imprint. Ideas and outlines suggested by AI were reviewed and chosen by the author.',
  'a.note': 'This counts the words AI inserted. It can’t see later rewriting, it isn’t legal advice, and it can’t promise what a store will decide.',
  'copy': 'Copy',
  'copied': 'Copied',
  'demo.c2': 'What’s included',

  /* what's included */
  'inc.eb': 'What’s included',
  'inc.h': 'Two ways to have Imprint. <em>The whole book</em> in both.',
  'inc.p': 'On its own, or inside the Snow AI account you already have. Imprint is being built; this is how it will be offered once the book steps are ready.',
  'plan1.h': 'Imprint on its own',
  'plan1.p': 'For an author who only needs the book studio. Its own page, its own plan, the Snow AI sign-in.',
  'price.b': 'Pricing is being set',
  'price.s': 'No figure until it’s final',
  'plan1.t1': 'Idea, title, outline and chapters',
  'plan1.t2': 'Drafts from your brief and sources',
  'plan1.t3': 'The Word and PDF files, and the AI disclosure helper',
  'plan.more': 'See Snow AI plans',
  'plan2.flag': 'For Snow AI customers',
  'plan2.h': 'Imprint inside your Snow AI account',
  'plan2.p': 'Add it to the account you use for other Snow AI apps. What your account already has is not charged again.',
  'plan2.t1': 'Everything in Imprint on its own',
  'plan2.t2': 'Ask, Reader and Render shared with your other apps, counted once',
  'plan2.t3': 'The same login across every app on the account',
  'save.b': 'Where the saving is',
  'save.p': 'Imprint is built on three Snow AI capabilities: Ask for ideas, outlines and drafts, Reader for PDF sources, and Render for the Word and PDF files. Bought one by one, each is its own subscription. Inside a Snow AI account each is held once, whichever product brought it, so Imprint adds only what the account doesn’t have yet.',
  'incl.h': 'What’s included where',
  'it.cap': 'Capability',
  'it.alone': 'Imprint on its own',
  'it.inside': 'Inside your Snow AI account',
  'it.yes': 'Included',
  'it.1': 'Your books list and the studio<small>Ready today</small>',
  'it.2': 'Idea, title options and outline<small>In build</small>',
  'it.3': 'Chapter drafts<small>In build · through Snow AI Ask</small>',
  'it.3b': 'The Ask your account already has, usage pooled',
  'it.4': 'PDF sources read<small>In build · through Snow AI Reader</small>',
  'it.4b': 'The same Reader as your other apps',
  'it.5': 'Word and PDF files<small>In build · through Snow AI Render</small>',
  'it.5b': 'The same Render as your other apps',
  'it.6': 'AI disclosure helper<small>In build</small>',
  'it.7': 'Dictation on every box<small>In build</small>',
  'it.8': 'Snow AI sign-in<small>Ready today</small>',
  'it.8a': 'Opens Imprint',
  'it.8b': 'One login for every app on the account',
  'it.soon': 'Later, in both',
  'soon.1': 'EPUB',
  'soon.2': 'Print-ready PDF, trim size and bleed',
  'soon.3': 'A cover',
  'soon.4': 'Filing a book in Documents',
  'soon.5': 'Word import',
  'soon.6': 'Imprint inside other apps',
  'never': '<b>A Snow AI customer never pays for the same thing twice.</b> If your account already has Ask, Reader or Render through another Snow AI product, Imprint uses it and doesn’t charge for it again.',

  /* the family */
  'fam.eb': 'Part of Snow AI',
  'fam.h': 'An article, a book. Your name on both.',
  'fam.p': 'Imprint is one app in the Snow AI family, built from its sibling Byline: the same sign-in, the same look, the same care with your facts.',
  'fam.1h': 'Byline, for articles',
  'fam.1p': 'A byline puts your name on an article; an imprint puts it on a book. Byline is where articles are written and published to Playbook.',
  'fam.1a': 'About Byline',
  'fam.2h': 'Documents, for keeping it',
  'fam.2p': 'Filing a finished book in Snow AI Documents comes later, with Documents’ intake door. Until then, the files are yours to download.',
  'fam.2a': 'About Documents',
  'fam.3h': 'One Snow AI sign-in',
  'fam.3p': 'Sign in once at snowai.app and the studio is open, with every other app on your account behind the same login.',
  'fam.3a': 'See the apps',

  /* questions */
  'faq.eb': 'Questions',
  'faq.h': 'Asked before chapter one.',
  'faq.p': 'Something else? Write to support and a person will answer.',
  'q1': 'Can I use Imprint today?',
  'a1': 'Not for a whole book yet. The studio is up with the Snow AI sign-in and your list of books. The idea, title and outline come next, then the chapters and drafts, the AI disclosure helper, sources, and the Word and PDF export.',
  'q2': 'Does it write fiction?',
  'a2': 'No. Imprint is for nonfiction written from your own expertise: a client guide, a handbook, a lead-magnet book. There are no fiction features.',
  'q3': 'Will a draft make things up?',
  'a3': 'A chapter draft uses only the chapter’s brief and the sources you tick. It never invents a fact, figure, name, quote or citation: a gap is written [need a figure] or [need a source], and a final file waits until every gap is filled.',
  'q4': 'Does Imprint publish my book anywhere?',
  'a4': 'No. Nothing publishes and nothing sends. Imprint makes a Word file and a PDF that you download, and you decide what happens next.',
  'q5': 'What about Amazon KDP’s question on AI?',
  'a5': 'KDP asks whether a book has AI-generated text. Imprint records how many words each draft inserted, per chapter, and gives you a statement to adapt for the form. It can’t see your later rewriting, it isn’t legal advice, and it can’t promise what a store will decide.',
  'q6': 'Can anyone else see my book?',
  'a6': 'No. A book, its chapters and its sources are their author’s alone. There is no shared editing and no one else’s view, including the people who run Imprint.',
  'q7': 'Can I include a client’s story?',
  'a7': 'Never a real person’s health details. An example person is invented and labelled as invented in the book. Every book is general education, not advice for one reader.',
  'q8': 'How much will it cost?',
  'a8': 'Pricing is being set, and no figure will appear here until it’s final. A Snow AI customer never pays for the same thing twice: what your account already has through another Snow AI product is not charged again.',

  /* closing and foot */
  'close.h': 'Your expertise, <em>between two covers.</em>',
  'close.p': 'Sign in with your Snow AI account to see the studio as it’s built. Your books are kept for you alone.',
  'close.c2': 'About Byline',
  'foot.about': 'Where a book is written from your own expertise, from an idea to a Word file and a PDF. Part of the Snow AI family.',
  'foot.imprint': 'Imprint',
  'foot.family': 'The family',
  'foot.byline': 'Byline',
  'foot.playbook': 'Playbook',
  'foot.documents': 'Documents',
  'foot.pitch': 'Pitch',
  'foot.model': 'Model',
  'foot.snowai': 'Snow AI',
  'foot.home': 'Home',
  'foot.products': 'Products',
  'foot.pricing': 'Pricing',
  'foot.privacy': 'Privacy',
  'foot.terms': 'Terms',
  'foot.help': 'Help',
  'foot.helpP': 'Questions about Imprint, or about writing your book with it? Write to us.',
  'foot.c': '© 2026 Snow AI',
  'foot.fine': 'Books are general education, not advice. The book, author and chapters on this page are invented examples.',
} as const;

export type Key = keyof typeof W;

/** {name} in a value, filled in. */
export function fill(s: string, vars: Record<string, string | number>): string {
  return s.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
}

/** The invented book's eight chapters: title and summary. */
export const CHAPTERS: [string, string][] = [1, 2, 3, 4, 5, 6, 7, 8].map((n) => [W[`ch.${n}` as Key], W[`ch.${n}s` as Key]]);
