import {
  AudioLines,
  BookOpen,
  Building2,
  Clapperboard,
  ClipboardList,
  Compass,
  Contact,
  Database,
  DoorOpen,
  Feather,
  FileOutput,
  Files,
  FlaskConical,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  Landmark,
  LayoutDashboard,
  type LucideIcon,
  MessageCircleQuestionMark,
  Mic,
  Newspaper,
  PenLine,
  Presentation,
  Quote,
  Receipt,
  ScanText,
  Send,
  ShieldCheck,
  SlidersHorizontal,
  Snowflake,
  Sprout,
  Target,
  Users,
} from 'lucide-react';
import type { GlyphName } from './apps';

/**
 * Each app's tile glyph, by its Lucide name. Imported one by one, so a page
 * carries these 34 icons and not the whole set. Copied with the kit; a new
 * app's glyph is added here and in `GlyphName` together.
 */
export const GLYPHS: Record<GlyphName, LucideIcon> = {
  snowflake: Snowflake,
  files: Files,
  'pen-line': PenLine,
  receipt: Receipt,
  'shield-check': ShieldCheck,
  'scan-text': ScanText,
  'file-output': FileOutput,
  landmark: Landmark,
  'sliders-horizontal': SlidersHorizontal,
  'clipboard-list': ClipboardList,
  contact: Contact,
  'door-open': DoorOpen,
  'hand-coins': HandCoins,
  users: Users,
  mic: Mic,
  'audio-lines': AudioLines,
  send: Send,
  presentation: Presentation,
  clapperboard: Clapperboard,
  target: Target,
  'message-circle-question-mark': MessageCircleQuestionMark,
  compass: Compass,
  quote: Quote,
  gift: Gift,
  newspaper: Newspaper,
  feather: Feather,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  sprout: Sprout,
  'heart-pulse': HeartPulse,
  'building-2': Building2,
  'layout-dashboard': LayoutDashboard,
  'flask-conical': FlaskConical,
  database: Database,
};

/** The family's interface stroke (standard 3.5). */
export const STROKE = 1.75;
